# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BankingiOSApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BankingiOSApp

  pod 'EncryptedCoreData', :git => 'https://github.com/project-imas/encrypted-core-data.git'

  target 'BankingiOSAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BankingiOSAppUITests' do
    # Pods for testing
  end

end
