package net.dankito.banking.fints.messages.segmente.implementierte.sepa


enum class PaymentInformationMessages(val xmlTemplate: String) {

    Pain_001_001_03("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Document xmlns=\"urn:iso:std:iso:20022:tech:xsd:pain.001.001.03\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"urn:iso:std:iso:20022:tech:xsd:pain.001.001.03 pain.001.001.03.xsd\"><CstmrCdtTrfInitn><GrpHdr><MsgId>\$MessageId\$</MsgId><CreDtTm>\$CreationDateTime\$</CreDtTm><NbOfTxs>\$NumberOfTransactions\$</NbOfTxs><CtrlSum>\$Amount\$</CtrlSum><InitgPty><Nm>\$DebitorName\$</Nm></InitgPty></GrpHdr><PmtInf><PmtInfId>\$PaymentInformationId\$</PmtInfId><PmtMtd>TRF</PmtMtd><NbOfTxs>\$NumberOfTransactions\$</NbOfTxs><CtrlSum>\$Amount\$</CtrlSum><PmtTpInf><SvcLvl><Cd>SEPA</Cd></SvcLvl></PmtTpInf><ReqdExctnDt>\$RequestedExecutionDate\$</ReqdExctnDt><Dbtr><Nm>\$DebitorName\$</Nm></Dbtr><DbtrAcct><Id><IBAN>\$DebitorIban\$</IBAN></Id></DbtrAcct><DbtrAgt><FinInstnId><BIC>\$DebitorBic\$</BIC></FinInstnId></DbtrAgt><ChrgBr>SLEV</ChrgBr><CdtTrfTxInf><PmtId><EndToEndId>NOTPROVIDED</EndToEndId></PmtId><Amt><InstdAmt Ccy=\"EUR\">\$Amount\$</InstdAmt></Amt><CdtrAgt><FinInstnId><BIC>\$RecipientBic\$</BIC></FinInstnId></CdtrAgt><Cdtr><Nm>\$RecipientName\$</Nm></Cdtr><CdtrAcct><Id><IBAN>\$RecipientIban\$</IBAN></Id></CdtrAcct><RmtInf><Ustrd>\$Reference\$</Ustrd></RmtInf></CdtTrfTxInf></PmtInf></CstmrCdtTrfInitn></Document>"),

    Pain_001_003_03("<?xml version=\"1.0\" encoding=\"UTF-8\"?><Document xmlns=\"urn:iso:std:iso:20022:tech:xsd:pain.001.003.03\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"urn:iso:std:iso:20022:tech:xsd:pain.001.003.03 pain.001.003.03.xsd\"><CstmrCdtTrfInitn><GrpHdr><MsgId>\$MessageId\$</MsgId><CreDtTm>\$CreationDateTime\$</CreDtTm><NbOfTxs>\$NumberOfTransactions\$</NbOfTxs><InitgPty><Nm>\$DebitorName\$</Nm></InitgPty></GrpHdr><PmtInf><PmtInfId>\$PaymentInformationId\$</PmtInfId><PmtMtd>TRF</PmtMtd><BtchBookg>true</BtchBookg><NbOfTxs>\$NumberOfTransactions\$</NbOfTxs><CtrlSum>\$Amount\$</CtrlSum><PmtTpInf><SvcLvl><Cd>SEPA</Cd></SvcLvl></PmtTpInf><ReqdExctnDt>\$RequestedExecutionDate\$</ReqdExctnDt><Dbtr><Nm>\$DebitorName\$</Nm></Dbtr><DbtrAcct><Id><IBAN>\$DebitorIban\$</IBAN></Id></DbtrAcct><DbtrAgt><FinInstnId><BIC>\$DebitorBic\$</BIC></FinInstnId></DbtrAgt><ChrgBr>SLEV</ChrgBr><CdtTrfTxInf><PmtId><EndToEndId>NOTPROVIDED</EndToEndId></PmtId><Amt><InstdAmt Ccy=\"EUR\">\$Amount\$</InstdAmt></Amt><CdtrAgt><FinInstnId><BIC>\$RecipientBic\$</BIC></FinInstnId></CdtrAgt><Cdtr><Nm>\$RecipientName\$</Nm></Cdtr><CdtrAcct><Id><IBAN>\$RecipientIban\$</IBAN></Id></CdtrAcct><RmtInf><Ustrd>\$Reference\$</Ustrd></RmtInf></CdtTrfTxInf></PmtInf></CstmrCdtTrfInitn></Document>")

}